apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer
  namespace: argo-cd
  labels:
    env: prd
spec:
  source:
    helm:
      parameters:
        - name: env
          value: prd
