apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-echo-headers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-echo-headers
  template:
    metadata:
      labels:
        app: nginx-echo-headers
    spec:
      containers:
        - name: nginx-echo-headers
          image: brndnmtthws/nginx-echo-headers:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-echo-headers
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: nginx-echo-headers
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-echo-headers
  annotations:
    kubernetes.io/ingress.class: nginx
{{ if .Values.ipWhitelist }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.ipWhitelist }}
{{ end }}
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-echo-headers
                port:
                  number: 8080
