apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-helloworld
  namespace: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-helloworld
  template:
    metadata:
      labels:
        app: aks-helloworld
    spec:
      containers:
        - name: aks-helloworld
          image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
          ports:
            - containerPort: 80
          env:
            - name: TITLE
              value: {{ .Release.Name }}.dabaas.net
---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld
  namespace: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: aks-helloworld
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aks-helloworld
  namespace: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    # link.argocd.argoproj.io/external-link: https://{{ .Release.Name }}.dabaas.net
spec:
  rules:
    - host: {{ .Release.Name }}.dabaas.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aks-helloworld
                port:
                  number: 80
