apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipcheck
  template:
    metadata:
      labels:
        app: ipcheck
    spec:
      containers:
        - name: ipcheck
          image: ghcr.io/exabugs/ipcheck:202110220047
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ipcheck
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: ipcheck
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ipcheck
  annotations:
    kubernetes.io/ingress.class: nginx
{{ if .Values.ipWhitelist }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.ipWhitelist }}
{{ end }}
    nginx.ingress.kubernetes.io/custom-http-errors: "403"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Frame-Options 'SAMEORIGIN';
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ipcheck
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ipcheck-healthz
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /healthz
            pathType: Prefix
            backend:
              service:
                name: ipcheck
                port:
                  number: 8080

# matchValues: ['/api/system/alive'],
# matchValues: ['/api/auth/saml', '/samlAuth'],

# Rate-Limitting per host
# https://docs.giantswarm.io/advanced/ingress/configuration/#rate-limiting
