apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipcheck
  template:
    metadata:
      labels:
        app: ipcheck
    spec:
      containers:
        - name: ipcheck
          image: ghcr.io/exabugs/ipcheck:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ipcheck
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: ipcheck
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ipcheck
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ipcheck
                port:
                  number: 8080
