apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello6
spec:
  destination:
    name: ""
    namespace: hello6
    server: https://kubernetes.default.svc
  source:
    path: hello-world2
    repoURL: https://github.com/exabugs/test_helm
    targetRevision: HEAD
    helm:
      parameters:
        - name: favoriteDrink
          value: coffee-2021
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
