apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipcheck
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/exabugs/test_helm
    path: ipcheck
    targetRevision: HEAD
    helm:
      parameters:
        - name: host
          value: ipcheck.dabaas.net
        - name: ipWhitelist
          value: "153.246.11.138/32,113.37.158.32/29"
  destination:
    server: https://kubernetes.default.svc
    namespace: ipcheck
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
